# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{memories}
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Parker", "Gary Cheong"]
  s.date = %q{2011-01-25}
  s.description = %q{CouchDB has built in document versioning, but you can't rely on it for version control. This is an implementation of a version-as-attachments approach created by @jchris.moonmaster9000@gmail.com}
  s.email = %q{moonmaster9000@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "lib/memories.rb",
    "lib/memories/annotation.rb",
    "lib/memories/attachment.rb",
    "lib/memories/base.rb",
    "lib/memories/milestones_proxy.rb",
    "lib/memories/versions_proxy.rb"
  ]
  s.homepage = %q{http://github.com/moonmaster9000/memories}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Versioning for your couchrest_model documents.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<couchrest_model>, ["~> 1.0.0"])
    else
      s.add_dependency(%q<couchrest_model>, ["~> 1.0.0"])
    end
  else
    s.add_dependency(%q<couchrest_model>, ["~> 1.0.0"])
  end
end

